Repository supersfel/GAMALDA, pull requests merged in 2023-08, with the labels that each got.

#63 54 프로젝트 설정 페이지 기능 구현
  be/src/db_connection/db_connection.service.ts
  be/src/project/dto/Project.dto.ts
  be/src/project/project.controller.ts
  be/src/project/project.service.ts
  fe/src/api/project/api.ts
  fe/src/components/milestone/MilestoneHeader.tsx
  fe/src/components/modules/MyPageProject/MyPageProject.tsx
  fe/src/components/projectSet/ProjSetBody.tsx
  fe/src/components/projectSet/ProjSetDelete.tsx
  fe/src/components/projectSet/ProjSetInfo.tsx
  fe/src/components/projectSet/ProjSetMember.tsx
  fe/src/components/projectSet/ProjSetPrivate.tsx
  fe/src/components/projectSet/ProjSetSelect.tsx
  fe/src/components/projectSet/type.ts
  fe/src/pages/ProjectSet.tsx
  fe/src/styles/components/ProjectSet/_projsetbody.scss
  fe/src/styles/components/ProjectSet/_projsetselect.scss
  fe/src/styles/main.css
Labels: FE, BE

#66 62 계정 관리 페이지 fe & be
  be/src/account_manage/account_manage/account_manage.controller.ts
  be/src/account_manage/account_manage/account_manage.module.ts
  be/src/account_manage/account_manage/account_manage.service.ts
  be/src/app.module.ts
  be/src/db_connection/db_connection.service.ts
  be/src/project/project.service.ts
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/accountManage/api.ts
  fe/src/api/imgServer/api.ts
  fe/src/api/project/api.ts
  fe/src/components/accountManage/AccountManage.tsx
  fe/src/components/modules/Header/Header.tsx
  fe/src/components/modules/Modal/AccountInfoModal.tsx
  fe/src/components/modules/MyPageProject/MyPageProject.tsx
  fe/src/components/modules/Toast/Toast.tsx
  fe/src/pages/AccountManagePage.tsx
  fe/src/pages/MyPage.tsx
  fe/src/pages/ProjectSet.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/accountManage/_accountmanage.scss
  fe/src/styles/components/modules/modal/_generateProjectModal.scss
  fe/src/styles/components/mypage/_mypagecontentarea.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/utils/accountManage.ts
  fe/src/utils/httpApi.ts
Labels: FE, BE

#68 67 작업한 퍼블리싱 반응형 보수 작업
  fe/src/components/login/Naver_Login.tsx
  fe/src/components/modules/Header/Header.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/Milestone/_milestoneCalenda.scss
  fe/src/styles/components/login/_login_box.scss
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/components/modules/modal/_generateProjectModal.scss
  fe/src/styles/components/mypage/_mypagecontentarea.scss
  fe/src/styles/main.css
Labels: FE

#70 refactor(be): teamMember 컬럼 삭제에 대한 리펙토링
  be/src/db_connection/db_connection.service.ts
  be/src/project/dto/Project.dto.ts
  be/src/project/project.controller.ts
Labels: enhancement, BE

#71 65 마일스톤 블록 반응형 적용
  be/src/db_connection/db_connection.service.ts
  be/src/project/project.controller.ts
  be/src/project/project.service.ts
  fe/src/api/project/api.ts
  fe/src/components/milestone/MilestoneBasic.tsx
  fe/src/components/milestone/MilestoneBlock.tsx
  fe/src/components/milestone/MilestoneBody.tsx
  fe/src/components/milestone/MilestoneSummary.tsx
  fe/src/components/modules/Modal/Milestone/BigModalChangeInfo.tsx
  fe/src/components/projectSet/ProjSetBody.tsx
  fe/src/components/projectSet/ProjSetInfo.tsx
  fe/src/modules/milestoneBlock/thunks.ts
  fe/src/pages/ProjectSet.tsx
  fe/src/styles/components/Milestone/_milestoneBlock.scss
  fe/src/styles/components/Milestone/_milestoneHeader.scss
  fe/src/styles/components/ProjectSet/_projsetbody.scss
  fe/src/styles/components/modules/modal/_bigModalChangeInfo.scss
  fe/src/styles/components/modules/modal/_smallModalChangeInfo.scss
  fe/src/styles/main.css
  fe/src/styles/main.css.map
  fe/src/styles/main.scss
  fe/src/styles/pages/_milestone.scss
  fe/src/utils/milestone.tsx
Labels: FE
