Repository supersfel/GAMALDA, pull requests merged in 2023-09, with the labels that each got.

#74 73 프로젝트 이미지 업로드 및 적용 작업
  fe/src/assets/png/gamaldaIcon.png
  fe/src/components/accountManage/AccountManage.tsx
  fe/src/components/milestone/Calendar/CalendarBlock.tsx
  fe/src/components/milestone/Calendar/CalendarCell.tsx
  fe/src/components/milestone/Calendar/MilestoneCalendar.tsx
  fe/src/components/milestone/MilestoneBody.tsx
  fe/src/components/milestone/MilestoneHeader.tsx
  fe/src/components/modules/Modal/Milestone/BigModalShowBlocks.tsx
  fe/src/components/modules/Modal/myPage/EnterProjectModal.tsx
  fe/src/components/modules/MyPageProject/MyPageProject.tsx
  fe/src/components/projectSet/ProjSetInfo.tsx
  fe/src/components/projectSet/ProjSetSelect.tsx
  fe/src/modules/blockInfo/reducer.ts
  fe/src/modules/blockInfo/types.ts
  fe/src/styles/components/Milestone/_milestoneCalenda.scss
  fe/src/styles/components/Milestone/_milestoneHeader.scss
  fe/src/styles/components/ProjectSet/_projsetbody.scss
  fe/src/styles/components/ProjectSet/_projsetselect.scss
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/components/modules/modal/_bigModalShowBlocks.scss
  fe/src/styles/main.css
  fe/src/utils/imageManage.ts
Labels: enhancement, FE, BE

#75 72 restful 한 api를 만들기 위한 url uri 작업
  be/src/account_manage/account_manage/account_manage.controller.ts
  be/src/block/block.controller.ts
  be/src/project/project.controller.ts
  fe/src/api/accountManage/api.ts
  fe/src/api/project/api.ts
  fe/src/components/projectSet/ProjSetInfo.tsx
  fe/src/pages/ProjectSet.tsx
  fe/src/utils/httpApi.ts
Labels: enhancement, FE, BE

#77 76 프로젝트 대표 썸네일 관련 버그 핫픽스
  fe/src/api/project/api.ts
  fe/src/components/projectSet/ProjSetInfo.tsx
Labels: bug, FE

#80 feat(fe): 달력에서 블럭이 없는 날은 See Event 문구 삭제
  fe/src/components/milestone/Calendar/CalendarCell.tsx
Labels: FE

#82 81 네이버 로그인 api 사용 검수를 위한 추가 작업
  be/src/login/user/user.service.ts
  fe/src/components/accountManage/AccountManage.tsx
  fe/src/hooks/useVerifingUserState.tsx
  fe/src/modules/userInfo/actions.ts
  fe/src/modules/userInfo/reducer.ts
  fe/src/modules/userInfo/types.ts
  fe/src/pages/AccountManagePage.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/accountManage/_accountmanage.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/styles/pages/_accountManage.scss
Labels: FE

#83 78 소개페이지 이미지변경 버그수정
  .DS_Store
  be/src/block/block.controller.ts
  be/src/socket/socket.gateway.ts
  fe/src/api/project/api.ts
  fe/src/assets/png/introduce_1.png
  fe/src/assets/png/introduce_2.png
  fe/src/assets/png/introduce_3.png
  fe/src/components/introduce/Intro_1.tsx
  fe/src/components/introduce/Intro_2.tsx
  fe/src/components/introduce/Intro_3.tsx
  fe/src/components/milestone/Calendar/CalendarCell.tsx
  fe/src/components/milestone/Calendar/CalendarHeader.tsx
  fe/src/components/milestone/Calendar/MilestoneCalendar.tsx
  fe/src/components/milestone/MilestoneBody.tsx
  fe/src/components/modules/Header/Header.tsx
  fe/src/modules/milestoneBlock/thunks.ts
  fe/src/pages/Milestone.tsx
  fe/src/styles/components/introduce/_intro_2.scss
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/main.css
  fe/src/styles/main.css.map
  fe/src/utils/milestone.tsx
Labels: FE

#85 style(fe): 반응형 작업 수정(헤더, 마이페이지에서의 버튼 font-size)
  fe/src/components/modules/Header/Header.tsx
  fe/src/pages/AccountManagePage.tsx
  fe/src/pages/Introduce.tsx
  fe/src/pages/Milestone.tsx
  fe/src/pages/MyPage.tsx
  fe/src/pages/ProjectSet.tsx
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/components/mypage/_mypagecontentarea.scss
  fe/src/styles/main.css
Labels: bug, FE
