Repository supersfel/GAMALDA, pull requests merged in 2023-01, with the labels that each got.

#3 1 fe be 초기세팅
  .eslintrc.js
  .gitignore
  .prettierrc
  be/.eslintrc.js
  be/.gitignore
  be/.prettierrc
  be/README.md
  be/nest-cli.json
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/main.ts
  be/test/app.e2e-spec.ts
  be/test/jest-e2e.json
  be/tsconfig.build.json
  be/tsconfig.json
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/tsconfig.json
Labels: FE, BE

#5 4 prisma 연결
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/prisma/schema.prisma
  package-lock.json
  package.json
Labels: BE

#9 7 라우터 적용 소개 페이지 퍼블리싱
  fe/src/App.tsx
  fe/src/assets/png/example_1.png
  fe/src/assets/png/example_2.png
  fe/src/assets/png/example_3.png
  fe/src/assets/png/price.png
  fe/src/assets/svg/chart.svg
  fe/src/assets/svg/chat.svg
  fe/src/assets/svg/cog.svg
  fe/src/assets/svg/gamaldalogo.svg
  fe/src/assets/svg/man_01.svg
  fe/src/assets/svg/man_05.svg
  fe/src/assets/svg/moon.svg
  fe/src/assets/svg/notebook.svg
  fe/src/assets/svg/notebookchart.svg
  fe/src/assets/svg/pencil.svg
  fe/src/assets/svg/photo.svg
  fe/src/components/introduce/Intro_1.tsx
  fe/src/components/introduce/Intro_2.tsx
  fe/src/components/introduce/Intro_3.tsx
  fe/src/hooks/useWindowScrollEvent.tsx
  fe/src/index.tsx
  fe/src/pages/Introduce.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/introduce/_intro_1.scss
  fe/src/styles/components/introduce/_intro_2.scss
  fe/src/styles/components/introduce/_intro_3.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/styles/pages/_introduce.scss
  fe/src/styles/reset.css
Labels: FE
