Repository supersfel/GAMALDA, pull requests merged in 2023-02, with the labels that each got.

#11 10 소개페이지 수정
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.css
  fe/src/App.tsx
  fe/src/components/introduce/Intro_1.tsx
  fe/src/components/introduce/Intro_3.tsx
  fe/src/styles/components/introduce/_intro_1.scss
  fe/src/styles/components/introduce/_intro_2.scss
  fe/src/styles/main.css
Labels: FE

#13 6 상단 네비게이션 컴포넌트 개발
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/assets/svg/gamaldaIcon.svg
  fe/src/assets/svg/home.svg
  fe/src/assets/svg/logout.svg
  fe/src/assets/svg/setting.svg
  fe/src/assets/svg/user.svg
  fe/src/assets/svg/userIcon.svg
  fe/src/components/modules/Header/Header.tsx
  fe/src/components/modules/Modal/AccountInfoModal.tsx
  fe/src/components/modules/Modal/ModalPortal.tsx
  fe/src/pages/Introduce.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
Labels: FE

#15 14 토스트 모듈 작성
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/modules/Toast/Toast.tsx
Labels: FE

#16 6 상단 네비게이션 컴포넌트 개발
  fe/src/assets/svg/home.svg
  fe/src/assets/svg/logout.svg
  fe/src/assets/svg/setting.svg
  fe/src/components/modules/Header/Header.tsx
  fe/src/components/modules/Modal/AccountInfoModal.tsx
  fe/src/hooks/useBackgroundClick.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/modules/header/_header.scss
  fe/src/styles/main.css
Labels: FE

#19 18 네이버 로그인
  fe/.gitignore
  fe/public/index.html
  fe/src/App.tsx
  fe/src/assets/png/naver_login.png
  fe/src/assets/svg/naver_login.svg
  fe/src/components/login/Naver_Login.tsx
  fe/src/components/modules/Header/Header.tsx
  fe/src/components/modules/Modal/AccountInfoModal.tsx
  fe/src/pages/Introduce.tsx
  fe/src/pages/Login.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/login/_login_box.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/styles/pages/_login.scss
Labels: FE

#21 20 socketio 적용 & mocks 적용
  be/.eslintrc.js
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/socket/socket.gateway.ts
  be/src/socket/socket.module.ts
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/api/project/api.ts
  fe/src/api/project/apiType.ts
  fe/src/components/milestone/MilestoneBasic.tsx
  fe/src/index.tsx
  fe/src/mocks/handlers.ts
  fe/src/mocks/worker.ts
  fe/src/pages/Milestone.tsx
Labels: FE, BE

#23 22 마일스톤페이지 박스헤더 퍼블리싱
  fe/package-lock.json
  fe/package.json
  fe/src/api/project/api.ts
  fe/src/api/project/apiType.ts
  fe/src/assets/svg/Calendar.svg
  fe/src/assets/svg/assignment.svg
  fe/src/assets/svg/off-rounded.svg
  fe/src/assets/svg/on-rounded.svg
  fe/src/assets/svg/pencil-02.svg
  fe/src/assets/svg/search.svg
  fe/src/components/milestone/MilestoneBasic.tsx
  fe/src/components/milestone/MilestoneHeader.tsx
  fe/src/hooks/useReactQuery.tsx
  fe/src/index.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/Milestone.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/Milestone/_milestoneHeader.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/utils/utils.ts
Labels: FE

#25 24 마일스톤 basic 퍼블리싱
  fe/src/components/milestone/MilestoneBasic.tsx
  fe/src/components/milestone/MilestoneBody.tsx
  fe/src/hooks/useWindowSize.tsx
  fe/src/pages/Milestone.tsx
  fe/src/styles/_common.scss
  fe/src/styles/components/Milestone/_milestoneBasic.scss
  fe/src/styles/components/Milestone/_milestoneBody.scss
  fe/src/styles/main.css
  fe/src/styles/main.scss
  fe/src/utils/time.ts
  fe/src/utils/utils.ts
Labels: FE, BE

#27 18 네이버 로그인
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/login/auth/auth.controller.ts
  be/src/login/auth/auth.module.ts
  be/src/login/auth/auth.service.ts
  be/src/login/auth/guard/naver-auth.guard.ts
  be/src/login/strategy/naver.strategy.ts
  be/src/login/user/user.dto.ts
  be/src/login/user/user.service.ts
  be/src/main.ts
  be/src/middlewares/logger.middleware.ts
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/api/project/api.ts
  fe/src/components/login/Naver_Login.tsx
  fe/src/components/modules/Header/Header.tsx
  fe/src/pages/LoginLoading.tsx
  package-lock.json
  package.json
Labels: BE
